[package]
name = "cosmic-applet-ollama"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = "fat"

[dependencies]
serde = { version = "1.0.202", features = ["derive"] }
serde_json = "1.0.117"
reqwest = { version = "0.12.4", features = ["json", "stream"] }
tokio = { version = "1", features = ["full"] }
i18n-embed = { version = "0.14.1", features = [
	"fluent-system",
	"desktop-requester",
] }
i18n-embed-fl = "0.8"
anyhow = "1.0.86"
rust-embed = "8.4.0"
once_cell = "1.19.0"

[dependencies.libcosmic]
git = "https://github.com/pop-os/libcosmic"
default-features = false
features = [
	"applet",
	"applet-token",
	"tokio",
	"wayland",
	"desktop",
	"dbus-config",
]
